export const ENEMIES = {
  wraith: {
    id: 'wraith',
    name: '游魂',
    desc: '最常见的夜行魂魄',
    lore: '从坟头飘来的淡衣影子。血少，但数量会把路堵死。',
    hp: 155,
    speed: 25,
    dps: 80,
    color: '#c9e8d8',
  },
  paperdoll: {
    id: 'paperdoll',
    name: '纸人',
    desc: '纸甲破后会加快',
    lore: '丧仪纸扎。外层纸甲要先撕开，撕开后脚步反而更轻。',
    hp: 170,
    armor: 150,
    speed: 24,
    stripSpeed: 1.38,
    dps: 80,
    color: '#f3efe4',
  },
  bellcorpse: {
    id: 'bellcorpse',
    name: '铜铃尸',
    desc: '厚甲坦克，走得慢',
    lore: '身上挂满镇墓铜铃，箭要射很久。长明灯的火箭克它。',
    hp: 220,
    armor: 430,
    speed: 18,
    dps: 80,
    color: '#6b5a3a',
  },
  nighttanuki: {
    id: 'nighttanuki',
    name: '狸奴',
    desc: '血少但极快',
    lore: '夜里变成人形的狸。霜梅一射，它就跑不动了。',
    hp: 95,
    speed: 54,
    dps: 80,
    color: '#6a4630',
  },
  vaultpaper: {
    id: 'vaultpaper',
    name: '跳纸人',
    desc: '会跳过遇到的第一株仙草',
    lore: '扛着竹竿的高纸人。第一株挡路的会被它跃过去。',
    hp: 190,
    speed: 28,
    dps: 80,
    vault: true,
    color: '#efe6d2',
  },
  shanxiao: {
    id: 'shanxiao',
    name: '山魈',
    desc: '关卡头目，受击后会暴起',
    lore: '山中独脚精。挨打会暴起加速，要用路障和火力一起拖。',
    hp: 2600,
    speed: 17,
    dps: 130,
    rageOnHit: 1.35,
    rageSpeed: 1.55,
    boss: true,
    color: '#a33a2a',
  },
};

export const ENEMY_ORDER = [
  'wraith',
  'paperdoll',
  'bellcorpse',
  'nighttanuki',
  'vaultpaper',
  'shanxiao',
];
